export const componentRegistry = {
  'alert': () => import('@todovue/tv-alert/demo'),
  'breadcrumbs': () => import('@todovue/tv-breadcrumbs/demo'),
  'button': () => import('@todovue/tv-button/demo'),
  'demo': () => import('@todovue/tv-demo/demo'),
  'hero': () => import('@todovue/tv-hero/demo'),
  'label': () => import('@todovue/tv-label/demo'),
  'menu': () => import('@todovue/tv-menu/demo'),
  'modal': () => import('@todovue/tv-modal/demo'),
  'pagination': () => import('@todovue/tv-pagination/demo'),
  'relativetime': () => import('@todovue/tv-relative-time/demo'),
  'search': () => import('@todovue/tv-search/demo'),
  'sidebar': () => import('@todovue/tv-sidebar/demo'),
  'themebutton': () => import('@todovue/tv-theme-button/demo'),
};
